services:
  cutoff-updater:
    build: .
    env_file:
      - .env
    volumes:
      - ./cdn:/app/cdn
    restart: unless-stopped

  fileserver:
    image: nginx:alpine
    ports:
      - "4000:80"
    volumes:
      - ./cdn:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

    restart: unless-stopped
