name: Update LP Cutoff

on:
  schedule:
    - cron: '10 0 * * *'  # Runs at 00:10 UTC every day
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Create directories
      run: |
        mkdir -p docs/current
        date_dir="docs/$(date +'%Y-%m-%d')"
        mkdir -p "$date_dir"

    - name: Update cutoff
      run: |
        python update_cutoff.py
        cp lp_cutoffs.json docs/current/cutoffs.json
        date_dir="docs/$(date +'%Y-%m-%d')"
        cp lp_cutoffs.json "$date_dir/cutoffs.json"
      env:
        API_KEY: ${{ secrets.RIOT_API_KEY }}
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add docs/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update cutoffs for $(date +'%Y-%m-%d')" && git push)
