name: Update LP Cutoff

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'
    
    - name: Create directories
      run: |
        mkdir -p cdn/current
        date_dir="cdn/$(date +'%Y-%m-%d')"
        mkdir -p "$date_dir"

    - name: Update cutoff
      run: |
        go run main.go
        cp cutoffs.json cdn/current/cutoffs.json
        date_dir="cdn/$(date +'%Y-%m-%d')"
        cp cutoffs.json "$date_dir/cutoffs.json"
      env:
        API_KEY: ${{ secrets.RIOT_API_KEY }}
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add cdn/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update cutoffs for $(date +'%Y-%m-%d')" && git push)
